title: IndieGo Discord Bot
description: This is the official website for the IndieGo Discord Bot.
theme: minima

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Author information
author:
  name: Your Name
  email: your-email@example.com

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed